### PR TITLE
Update : Use github images to host the image.

### PR DESCRIPTION
**Pull request by baseplate-admin**
Title

### CODE REVIEW

**Comment by baseplate-admin** [comment]
@TanimSk Merge this

**Comment by TanimSk** [comment]
If the user's offline, whats the approach then?
However, I am merging this.
Thanks bruh

**Comment by baseplate-admin** [comment]
@TanimSk It is tied to my account. As long as i exist. This repo exists. This wont go away :)

**Comment by baseplate-admin** [comment]
Thanks for merging 📦

**Pull request merged**
